version: '3'

services:
  db:
    image: postgres:15.3
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: estacja2
  api:
    image: docker.io/bitnami/symfony:6.2
    ports:
      - '8000:8000'
    environment:
      APP_ENV: dev
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      ALLOW_EMPTY_PASSWORD: yes
      SYMFONY_DATABASE_HOST: mariadb
      SYMFONY_DATABASE_PORT_NUMBER: 3306
      SYMFONY_DATABASE_USER: api
      SYMFONY_DATABASE_NAME: estacja2
    volumes:
      - ./backend:/app
    depends_on:
      - mariadb
