version: '3'

services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./backend/:/var/www/symfony
    ports:
      - 8001:80
    networks:
      - symfony
  php:
    build:
      context: ./backend
    environment:
      APP_ENV: dev
    volumes:
      - ./backend:/var/www/symfony/
    networks:
      - symfony

networks:
  symfony: